# Generated by Django 5.1.15 on 2026-06-01 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COMMENT_REPLY', 'Comment Reply'), ('COMMENT_APPROVED', 'Comment Approved'), ('POST_COMMENT', 'New Comment on Post'), ('POST_PUBLISHED', 'Post Published'), ('WELCOME', 'Welcome')], db_index=True, max_length=30, verbose_name='type')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='is read')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_31a7e3_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a4f9a3_idx')],
            },
        ),
    ]
