# Generated by Django 5.1.15 on 2026-06-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_vector',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='search vector'),
        ),
    ]
