# Generated by Django 5.1.15 on 2026-06-01 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'media tag',
                'verbose_name_plural': 'media tags',
                'db_table': 'media_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/%Y/%m/', verbose_name='file')),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME type')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='file size (bytes)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width (px)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height (px)')),
                ('alt_text', models.CharField(blank=True, max_length=500, verbose_name='alt text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
                'db_table': 'media',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uploaded_by', 'created_at'], name='media_uploade_fc9b20_idx'), models.Index(fields=['mime_type'], name='media_mime_ty_b43728_idx'), models.Index(fields=['created_at'], name='media_created_3b0875_idx')],
            },
        ),
    ]
