# Generated by Django 5.1.15 on 2026-06-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='thumbnails',
            field=models.JSONField(blank=True, default=dict, verbose_name='thumbnails'),
        ),
    ]
